// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: ezqueuegrpc.proto

package ezqueuegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName           string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	QueueName         string `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
	DelaySeconds      uint32 `protobuf:"varint,3,opt,name=DelaySeconds,proto3" json:"DelaySeconds,omitempty"`
	VisibilityTimeout uint32 `protobuf:"varint,4,opt,name=VisibilityTimeout,proto3" json:"VisibilityTimeout,omitempty"`
}

func (x *CreateParams) Reset() {
	*x = CreateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParams) ProtoMessage() {}

func (x *CreateParams) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParams.ProtoReflect.Descriptor instead.
func (*CreateParams) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateParams) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateParams) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateParams) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *CreateParams) GetVisibilityTimeout() uint32 {
	if x != nil {
		return x.VisibilityTimeout
	}
	return 0
}

type EnqueueParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName   string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	QueueName string `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *EnqueueParams) Reset() {
	*x = EnqueueParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueParams) ProtoMessage() {}

func (x *EnqueueParams) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueParams.ProtoReflect.Descriptor instead.
func (*EnqueueParams) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueParams) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *EnqueueParams) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *EnqueueParams) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeekParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName   string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	QueueName string `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
}

func (x *PeekParams) Reset() {
	*x = PeekParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeekParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekParams) ProtoMessage() {}

func (x *PeekParams) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekParams.ProtoReflect.Descriptor instead.
func (*PeekParams) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{2}
}

func (x *PeekParams) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *PeekParams) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DequeueParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName   string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	QueueName string `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
}

func (x *DequeueParams) Reset() {
	*x = DequeueParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueParams) ProtoMessage() {}

func (x *DequeueParams) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueParams.ProtoReflect.Descriptor instead.
func (*DequeueParams) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueParams) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DequeueParams) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type QueueItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *QueueItem) Reset() {
	*x = QueueItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueItem) ProtoMessage() {}

func (x *QueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueItem.ProtoReflect.Descriptor instead.
func (*QueueItem) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{4}
}

func (x *QueueItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReturnStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int32 `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *ReturnStatus) Reset() {
	*x = ReturnStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ezqueuegrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStatus) ProtoMessage() {}

func (x *ReturnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ezqueuegrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStatus.ProtoReflect.Descriptor instead.
func (*ReturnStatus) Descriptor() ([]byte, []int) {
	return file_ezqueuegrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnStatus) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

var File_ezqueuegrpc_proto protoreflect.FileDescriptor

var file_ezqueuegrpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x7a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x2c, 0x0a, 0x11, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x56, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x61,
	0x0a, 0x0d, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x44, 0x0a, 0x0a, 0x50, 0x65, 0x65, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x44, 0x65, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x25, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xa4, 0x01, 0x0a, 0x08, 0x45, 0x7a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x26,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0d, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x12, 0x0e, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x0d, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x25, 0x0a, 0x07, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x0e, 0x2e, 0x44, 0x65,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1f, 0x0a, 0x04, 0x50, 0x65, 0x65, 0x6b, 0x12,
	0x0b, 0x2e, 0x50, 0x65, 0x65, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x65, 0x7a,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ezqueuegrpc_proto_rawDescOnce sync.Once
	file_ezqueuegrpc_proto_rawDescData = file_ezqueuegrpc_proto_rawDesc
)

func file_ezqueuegrpc_proto_rawDescGZIP() []byte {
	file_ezqueuegrpc_proto_rawDescOnce.Do(func() {
		file_ezqueuegrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ezqueuegrpc_proto_rawDescData)
	})
	return file_ezqueuegrpc_proto_rawDescData
}

var file_ezqueuegrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ezqueuegrpc_proto_goTypes = []interface{}{
	(*CreateParams)(nil),  // 0: CreateParams
	(*EnqueueParams)(nil), // 1: EnqueueParams
	(*PeekParams)(nil),    // 2: PeekParams
	(*DequeueParams)(nil), // 3: DequeueParams
	(*QueueItem)(nil),     // 4: QueueItem
	(*ReturnStatus)(nil),  // 5: ReturnStatus
}
var file_ezqueuegrpc_proto_depIdxs = []int32{
	0, // 0: Ezqueued.Create:input_type -> CreateParams
	1, // 1: Ezqueued.Enqueue:input_type -> EnqueueParams
	3, // 2: Ezqueued.Dequeue:input_type -> DequeueParams
	2, // 3: Ezqueued.Peek:input_type -> PeekParams
	5, // 4: Ezqueued.Create:output_type -> ReturnStatus
	5, // 5: Ezqueued.Enqueue:output_type -> ReturnStatus
	4, // 6: Ezqueued.Dequeue:output_type -> QueueItem
	4, // 7: Ezqueued.Peek:output_type -> QueueItem
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ezqueuegrpc_proto_init() }
func file_ezqueuegrpc_proto_init() {
	if File_ezqueuegrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ezqueuegrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezqueuegrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezqueuegrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeekParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezqueuegrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezqueuegrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ezqueuegrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ezqueuegrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ezqueuegrpc_proto_goTypes,
		DependencyIndexes: file_ezqueuegrpc_proto_depIdxs,
		MessageInfos:      file_ezqueuegrpc_proto_msgTypes,
	}.Build()
	File_ezqueuegrpc_proto = out.File
	file_ezqueuegrpc_proto_rawDesc = nil
	file_ezqueuegrpc_proto_goTypes = nil
	file_ezqueuegrpc_proto_depIdxs = nil
}
